JavaScriptIntro/Models/PowerPlant.cs
namespace JavaScriptIntro.Models
{
    public class PowerPlant
    {
        public int id { get; set; }
        public string type { get; set; }
        public int powerGenerated { get; set; }
        public decimal maintenanceCost { get; set; }
        public string location { get; set; }
    }
}

JavaScriptIntro/Models/PowerPlantRepository.cs
using System.Collections.Generic;
using System.Linq;

namespace JavaScriptIntro.Models
{
    public class PowerPlantRepository
    {
        private static readonly IList<PowerPlant> PowerPlants = new List<PowerPlant>
            {
                new PowerPlant { id = 1, location = "Alexandria, VA", type = "Coal", powerGenerated = 75, maintenanceCost = 450m },
                new PowerPlant { id = 2, location = "Carson City, NV", type = "Oil", powerGenerated = 150, maintenanceCost = 900m },
                new PowerPlant { id = 3, location = "Shippingport, PA", type = "Nuclear", powerGenerated = 200, maintenanceCost = 1300m },
                new PowerPlant { id = 4, location = "Fowler, IN", type = "Wind", powerGenerated = 3, maintenanceCost = 80m },
                new PowerPlant { id = 5, location = "Austin, TX", type = "Solar", powerGenerated = 8, maintenanceCost = 145m },

                new PowerPlant { id = 6, location = "a", type = "Nuclear", powerGenerated = 200, maintenanceCost = 1300m },
                new PowerPlant { id = 7, location = "b", type = "Wind", powerGenerated = 3, maintenanceCost = 80m },
                new PowerPlant { id = 8, location = "c", type = "Solar", powerGenerated = 8, maintenanceCost = 145m },
                new PowerPlant { id = 9, location = "d", type = "Coal", powerGenerated = 75, maintenanceCost = 450m },
                new PowerPlant { id = 10, location = "e", type = "Oil", powerGenerated = 150, maintenanceCost = 900m },
                new PowerPlant { id = 11, location = "f", type = "Nuclear", powerGenerated = 200, maintenanceCost = 1300m },
                new PowerPlant { id = 12, location = "g", type = "Wind", powerGenerated = 3, maintenanceCost = 80m },
                new PowerPlant { id = 13, location = "h", type = "Solar", powerGenerated = 8, maintenanceCost = 145m },
            };

        public IEnumerable<PowerPlant> GetAll()
        {
            return PowerPlants;
        }

        public PowerPlant GetById(int id)
        {
            return PowerPlants.FirstOrDefault(x => x.id == id);
        }

        public void Add(PowerPlant powerPlant)
        {
            PowerPlants.Add(powerPlant);
        }

        public void DeleteById(int id)
        {

        }
    }
}

JavaScriptIntro/Controllers/AppController.cs
using System.Web.Mvc;

namespace JavaScriptIntro.Controllers
{
  public class AppController : Controller
  {
    public ActionResult Index()
    {
      return View();
    }
  }
}

JavaScriptIntro/Controllers/ExercisesController.cs
using System.Web.Mvc;

namespace JavaScriptIntro.Controllers
{
    public class ExercisesController : Controller
    {
        // 1.2 JavaScript Inheritance and Scope
        public ViewResult Exercises_1_2() { return View(); }

        // 1.4 Backbone.js Review
        public ViewResult Exercises_1_4() { return View(); }
        public ViewResult Exercises_1_4_End() { return View(); }

        // 2.1 Advanced Backbone Collections
        public ViewResult Exercises_2_1() { return View(); }

        // 2.2 Advanced Backbone Routes
        public ViewResult Exercises_2_2() { return View(); }

        // 2.3 Marionette Applications and Views
        public ViewResult Exercises_2_3() { return View(); }

        // 2.4 Marionette Regions and Events
        public ViewResult Exercises_2_4() { return View(); }
        public ViewResult Exercises_2_4_End() { return View(); }

        // 3.1 Require.js
        public ViewResult Exercises_3_1() { return View();  }
    }
}

JavaScriptIntro/Controllers/PowerPlantsController.cs
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using JavaScriptIntro.Models;

namespace JavaScriptIntro.Controllers
{
    public class PowerPlantsController : ApiController
    {
        private static readonly PowerPlantRepository PowerPlants = new PowerPlantRepository();

        // GET api/values
        public PowerPlant[] Get()
        {
            return PowerPlants.GetAll().Take(5).ToArray();
        }

        // GET api/values/5
        public HttpResponseMessage Get(int id)
        {
            var powerPlant = PowerPlants.GetById(id);

            if (powerPlant == null)
            {
                return new HttpResponseMessage(HttpStatusCode.NotFound);
            }

            return Request.CreateResponse(HttpStatusCode.OK, powerPlant);
        }

        // POST api/values
        public HttpResponseMessage Post([FromBody]PowerPlant value)
        {
            // TODO: Check for validity.
            value.id = PowerPlants.GetAll().Max(x => x.id) + 1;
            PowerPlants.Add(value);

            return new HttpResponseMessage(HttpStatusCode.Created);
        }

        // PUT api/values/5
        public void Put([FromBody]PowerPlant value)
        {
            var powerPlant = PowerPlants.GetById(value.id);
            powerPlant.location = value.location;
            powerPlant.type = value.type;
            powerPlant.powerGenerated = value.powerGenerated;
            powerPlant.maintenanceCost = value.maintenanceCost;
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
            PowerPlants.DeleteById(id);
        }
    }
}

JavaScriptIntro/Controllers/PowerPlantsV2Controller.cs
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using JavaScriptIntro.Models;

namespace JavaScriptIntro.Controllers
{
    public class PowerPlantsV2Controller : ApiController
    {
        private static readonly PowerPlantRepository PowerPlants = new PowerPlantRepository();

        // GET api/values
        public object Get()
        {
            return Get((int?)1);
        }

        public object Get([FromUri]int? page)
        {
            int pageIndex = (page ?? 1) - 1;
            return new
                {
                    powerplants = PowerPlants.GetAll().Skip(pageIndex * 5).Take(5).ToArray(),
                    page,
                    totalPages = PowerPlants.GetAll().Count() % 5
                };
        }

        // GET api/values/5
        public HttpResponseMessage Get(int id)
        {
            var powerPlant = PowerPlants.GetById(id);

            if (powerPlant == null)
            {
                return new HttpResponseMessage(HttpStatusCode.NotFound);
            }

            return Request.CreateResponse(HttpStatusCode.OK, powerPlant);
        }

        // POST api/values
        public HttpResponseMessage Post([FromBody]PowerPlant value)
        {
            // TODO: Check for validity.
            value.id = PowerPlants.GetAll().Max(x => x.id) + 1;
            PowerPlants.Add(value);

            return new HttpResponseMessage(HttpStatusCode.Created);
        }

        // PUT api/values/5
        public void Put([FromBody]PowerPlant value)
        {
            var powerPlant = PowerPlants.GetById(value.id);
            powerPlant.location = value.location;
            powerPlant.type = value.type;
            powerPlant.powerGenerated = value.powerGenerated;
            powerPlant.maintenanceCost = value.maintenanceCost;
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
            PowerPlants.DeleteById(id);
        }
    }
}

JavaScriptIntro/Controllers/ValuesController.cs
using System.Web.Http;

namespace JavaScriptIntro.Controllers
{
public class ValuesController : ApiController
{
    public class DeepModelChild
    {
        public string value { get; set; }
    }

    public class DeepModel
    {
        public string name { get; set; }
        public DeepModelChild child { get; set; }
    }

    // GET api/values
    public string[] Get()
    {
        return new [] { "1", "2", "3" };
    }

    // GET api/values/5
    public string Get(int id)
    {
        return id.ToString();
    }

    // POST api/values
    public void Post([FromBody]DeepModel value)
    {
    }

    // PUT api/values/5
    public void Put([FromBody]string value)
    {
    }

    // DELETE api/values/5
    public void Delete(int id)
    {
    }
}
}

JavaScriptIntro/Views/App/Index.cshtml
<h1>Hello!</h1>
<div id="main"></div>
<script id="tmpl-plantDetails" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <%= type %></p>
    <p><strong>Power Generated:</strong> <%= powerGenerated %> MW</p>
    <p><strong>Maintenance Cost:</strong> $<%= powerGenerated %></p>
    <button class="calculate">Calculate Cost Per MW</button>
</script>
<script id="tmpl-plantDetails24" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <%= type %></p>
    <p><strong>Power Generated:</strong> <input class="powerGenerated" type="number" value="<%= powerGenerated %>" /> MW</p>
    <p><strong>Maintenance Cost:</strong> $<%= powerGenerated %></p>
    <button class="calculate">Calculate Cost Per MW</button>
    <button class="save">Save</button>
</script>

@section script {
    <script src="~/Content/js/lib/jquery-1.9.1.js"></script>
    <script src="~/Content/js/lib/underscore-1.4.4.js"></script>
    <script src="~/Content/js/lib/backbone-1.0.0.js"></script>
    <script src="~/Content/js/app.js"></script>
    <script>
        $(function () {
            new PlantManager.Router();
            Backbone.history.start();
        });
    </script>
}

JavaScriptIntro/Views/Exercises/Exercise_1_2_Start.cshtml
<script>

    // Type your code here.
    var myName = 'Tim';
    document.write(myName);
    
    var carsIveOwned = [
        { make: 'Ford', model: 'Taurus', yearsOwned: 4 },
        { make: 'Dodge', model: 'Avenger', yearsOwned: 5 },
        { make: 'Ford', model: 'Focus', yearsOwned: 1 }
    ];
    
    var carLogger = {
        logCars: function (name, cars) {
            document.write(name);
            for (var i = 0; i < cars.length; i++) {
                document.write(cars[i]);
            }
        }
    };

</script>

JavaScriptIntro/Views/Exercises/Exercises_1_2.cshtml
<button id="upgrade">Upgrade</button>
<script>
    
var PowerPlant = function(powerGenerated) {
    this.powerGenerated = powerGenerated;
}
    
var SolarPowerPlant = function() {

    this.printPower = function() {
        console.log(this.powerGenerated);
    }
}

SolarPowerPlant.prototype = new PowerPlant();

var plant = new SolarPowerPlant();

plant.printPower();

upgrade.addEventListener("click", function() {

});
</script>

JavaScriptIntro/Views/Exercises/Exercises_1_2_End.cshtml
<button id="upgrade">Upgrade</button>
<script src="~/Content/js/lib/underscore-1.4.4.js"></script>
<script>

    // Steps 2-5
    var PowerPlant = function (powerGenerated) {
        this.powerGenerated = powerGenerated;
    };

    var SolarPowerPlant = function () {
        this.printPower = function () {
            console.log(this.powerGenerated);
        };
    };

    SolarPowerPlant.prototype = new PowerPlant(100);

    var solar = new SolarPowerPlant();
    solar.printPower();

    // Step 6
    var powerPlant = {
        upgrade: function () {
            console.log(this); // `this` is `powerPlant`
        }
    };
    foo.bar();

    // Step 7
    var PowerPlant = function () {
        console.log(this); // `this` is `PowerPlant`
    };

    // Step 8
    document.getElementById('upgrade').addEventListener('click', function () {
        console.log(this); // `this` is the button!
    });

    // Step 9

    var powerPlant = {
        powerGenerated: 100
    };

    var upgradePowerPlant = function () {
        this.powerGenerated = this.powerGenerated * 1.1;
        return this.powerGenerated;
    };

    console.log(upgradePowerPlant()); // NaN

    // Step 10
    console.log(upgradePowerPlant.call(powerPlant)); // 110

    /* console.log(_.bind(upgradePowerPlant, powerPlant)()); */

</script>

JavaScriptIntro/Views/Exercises/Exercises_1_4.cshtml
<div id="main"></div>
<script id="tmpl-powerPlant" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <%= type %></p>
    <p><strong>Maintenance Cost:</strong> $<%= maintenanceCost %></p>
    <p><strong>PowerGenerated:</strong> <%= powerGenerated %>MW</p>
</script>
<script src="~/Content/js/lib/jquery-1.9.1.js"></script>
<script src="~/Content/js/lib/underscore-1.4.4.js"></script>
<script src="~/Content/js/lib/backbone-1.0.0.js"></script>
<script>

    var PowerPlant = Backbone.Model.extend({
        urlRoot: "/api/powerplants"
    });

    var PowerPlantView = Backbone.View.extend({
        template: _.template($("#tmpl-powerPlant").html()),
        render: function() {
            this.$el.html(this.template(myPlant.toJSON()));

            return this;
        }
    });

    var AppRouter = Backbone.Router.extend({
        routes: {
            "powerplant/:id": "plant"
        },

        plant: function(id) {
            var myPlant = new PowerPlant({ id: id});

            myPlant.fetch({
                success: function() {
                    var plantHatchView = new PowerPlantView({ model: plantHatch});
                    $("#main").html(plantHatchView.render().el);
                }
            });
        }
    });

    $(function() {
        var router = new AppRouter();

        Backbone.history.start();
    });
</script>

JavaScriptIntro/Views/Exercises/Exercises_1_4_End.cshtml
<div id="main"></div>
<script id="tmpl-powerPlant" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <%= type %></p>
    <p><strong>Maintenance Cost:</strong> $<%= maintenanceCost %></p>
    <p><strong>PowerGenerated:</strong> <%= powerGenerated %>MW</p>
</script>
<script src="~/Content/js/lib/jquery-1.9.1.js"></script>
<script src="~/Content/js/lib/underscore-1.4.4.js"></script>
<script src="~/Content/js/lib/backbone-1.0.0.js"></script>
<script>

    // Finished
    var PowerPlant = Backbone.Model.extend({
        urlRoot: '/api/powerplants'
    });
    
    var PowerPlantView = Backbone.View.extend({
        template: _.template($('#tmpl-powerPlant').html()),
        render: function () {
            this.$el.html(this.template(this.model.toJSON()));
            return this;
        }
    });
    
    var powerPlant = new PowerPlant({
        location: 'Alexandria, VA',
        type: 'Coal',
        maintenanceCost: 450,
        powerGenerated: 75
    });
    
    // var view = new PowerPlantView({ model: powerPlant });
    // $('#main').html(view.render().el);
    
    var Router = Backbone.Router.extend({
        routes: {
            'powerplants/:id': 'details'
        },
        details: function (id) {
            var powerPlant = new PowerPlant({ id: id });
            powerPlant.fetch({
                success: function () {
                    var view = new PowerPlantView({ model: powerPlant });
                    $('#main').html(view.render().el);
                }
            });
        }
    });
    
    $(function () {
        new Router();
        Backbone.history.start();
    });

</script>

JavaScriptIntro/Views/Exercises/Exercises_2_1.cshtml
@section head {
    <script data-main="@Url.Content("~/Content/js/main-2.1.js")" src="~/Content/js/lib/require-2.1.5.js"></script>
}

<div id="main"></div>

<script id="tmpl-powerPlantListItem" type="text/template">
    <a href="#/powerplants/<%= id %>"><%= location %></a>
    <span><%= powerGenerated %></span>
</script>

<script id="tmpl-powerPlantDetails" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <input id="type" value="<%= type %>" /></p>
    <p><strong>Power Generated:</strong> <input id="powerGenerated" type="number" value="<%= powerGenerated %>" />MW</p>
    <p><strong>Maintenance Cost:</strong> $<input id="maintenanceCost" type="number" value="<%= maintenanceCost %>" /></p>
    <button id="save">Save</button>
    <a href="#/">Return to List</a>
</script>

JavaScriptIntro/Views/Exercises/Exercises_2_2.cshtml
@section head {
    <script data-main="@Url.Content("~/Content/js/main-2.2.js")" src="~/Content/js/lib/require-2.1.5.js"></script>
}

<div id="main"></div>

<script id="tmpl-powerPlantList" type="text/template">
    <table>
        <thead>
            <tr>
                <th>Location</th>
                <th>Type</th>
                <th>Power Generated</th>
                <th>Maintenance Cost</th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot>
            <tr>
                <br />
                <td colspan="4">
                    <% if (page > 1) { %>
                        <a href="#list/<%= page - 1%>">Previous</a>
                    <% } %>
                    <% if (page < totalPages) { %>
                        <a href="#list/<%= page + 1%>">Next</a>
                    <% } %>
                </td>
            </tr>
        </tfoot>
    </table>
</script>

<script id="tmpl-powerPlantListItem" type="text/template">
    <td><a href="#/powerplants/<%= id %>"><%= location %></a></td>
    <td><%= type %></td>
    <td><%= powerGenerated %>MW</td>
    <td>$<%= maintenanceCost %></td>
</script>

<script id="tmpl-powerPlantDetails" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <input id="type" value="<%= type %>" /></p>
    <p><strong>Power Generated:</strong> <input id="powerGenerated" type="number" value="<%= powerGenerated %>" />MW</p>
    <p><strong>Maintenance Cost:</strong> $<input id="maintenanceCost" type="number" value="<%= maintenanceCost %>" /></p>
    <button id="save">Save</button>
    <a href="#/">Return to List</a>
</script>

JavaScriptIntro/Views/Exercises/Exercises_2_3.cshtml
@section head {
    <script data-main="@Url.Content("~/Content/js/main-2.3.js")" src="~/Content/js/lib/require-2.1.5.js"></script>
}

<div id="main"></div>

<script id="tmpl-powerPlantList" type="text/template">
    <table>
        <thead>
            <tr>
                <th>Location</th>
                <th>Type</th>
                <th>Power Generated</th>
                <th>Maintenance Cost</th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot>
            <tr>
                <th colspan="4">
                    <% if (page > 1) { %>
                        <a href="#list/<%= page - 1 %>">Prev</a>
                    <% } %>
                    <% if (page < totalPages) { %>
                        <a href="#list/<%= page + 1 %>">Next</a>
                    <% } %>
                </th>
            </tr>
        </tfoot>
    </table>
</script>

<script id="tmpl-powerPlantListItem" type="text/template">
    <td><a href="#/powerplants/<%= id %>"><%= location %></a></td>
    <td><%= type %></td>
    <td><%= powerGenerated %>MW</td>
    <td>$<%= maintenanceCost %></td>
</script>

<script id="tmpl-powerPlantDetails" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <input id="type" value="<%= type %>" /></p>
    <p><strong>Power Generated:</strong> <input id="powerGenerated" type="number" value="<%= powerGenerated %>" />MW</p>
    <p><strong>Maintenance Cost:</strong> $<input id="maintenanceCost" type="number" value="<%= maintenanceCost %>" /></p>
    <button id="save">Save</button>
    <a href="#/">Return to List</a>
</script>

JavaScriptIntro/Views/Exercises/Exercises_2_4.cshtml
@section head {
    <script data-main="@Url.Content("~/Content/js/main-2.4.js")" src="~/Content/js/lib/require-2.1.5.js"></script>
}

<div id="main"></div>

<script id="tmpl-powerPlantList" type="text/template">
    <table>
        <thead>
            <tr>
                <th>Location</th>
                <th>Type</th>
                <th>Power Generated</th>
                <th>Maintenance Cost</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</script>

<script id="tmpl-powerPlantListItem" type="text/template">
    <td><a href="#/powerplants/<%= id %>"><%= location %></a></td>
    <td><%= type %></td>
    <td><%= powerGenerated %>MW</td>
    <td>$<%= maintenanceCost %></td>
</script>

<script id="tmpl-powerPlantDetails" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <input id="type" value="<%= type %>" /></p>
    <p><strong>Power Generated:</strong> <input id="powerGenerated" type="number" value="<%= powerGenerated %>" />MW</p>
    <p><strong>Maintenance Cost:</strong> $<input id="maintenanceCost" type="number" value="<%= maintenanceCost %>" /></p>
    <button id="save">Save</button>
    <a href="#/">Return to List</a>
</script>

JavaScriptIntro/Views/Exercises/Exercises_2_4_End.cshtml
@section head {
    <script data-main="@Url.Content("~/Content/js/main-2.4-end.js")" src="~/Content/js/lib/require-2.1.5.js"></script>
}

<div id="main"></div>

<script id="tmpl-powerPlantList" type="text/template">
    <table>
        <thead>
            <tr>
                <th>Location</th>
                <th>Type</th>
                <th>Power Generated</th>
                <th>Maintenance Cost</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</script>

<script id="tmpl-powerPlantListItem" type="text/template">
    <td><a href="#/powerplants/<%= id %>"><%= location %></a></td>
    <td><%= type %></td>
    <td><%= powerGenerated %>MW</td>
    <td>$<%= maintenanceCost %></td>
</script>

<script id="tmpl-powerPlantDetails" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <input id="type" value="<%= type %>" /></p>
    <p><strong>Power Generated:</strong> <input id="powerGenerated" type="number" value="<%= powerGenerated %>" />MW</p>
    <p><strong>Maintenance Cost:</strong> $<input id="maintenanceCost" type="number" value="<%= maintenanceCost %>" /></p>
    <button id="save">Save</button>
    <a href="#/">Return to List</a>
</script>

JavaScriptIntro/Views/Exercises/Exercises_3_1.cshtml
<div id="main"></div>

<script id="tmpl-powerPlantListItem" type="text/template">
    <a href="#/powerplants/<%= id %>"><%= location %></a>
</script>

<script id="tmpl-powerPlantDetails" type="text/template">
    <h2><%= location %></h2>
    <p><strong>Type:</strong> <input id="type" value="<%= type %>" /></p>
    <p><strong>Power Generated:</strong> <input id="powerGenerated" type="number" value="<%= powerGenerated %>" />MW</p>
    <p><strong>Maintenance Cost:</strong> $<input id="maintenanceCost" type="number" value="<%= maintenanceCost %>" /></p>
    <button id="save">Save</button>
    <a href="#/">Return to List</a>
</script>

<script src="~/Content/js/lib/jquery-1.9.1.js"></script>
<script src="~/Content/js/lib/underscore-1.4.4.js"></script>
<script src="~/Content/js/lib/backbone-1.0.0.js"></script>
<script>

    PlantManager = {

        start: function () {
            PlantManager.appView = new PlantManager.AppView();
            PlantManager.router = new PlantManager.Router();
            Backbone.history.start();
        }

    };

    PlantManager.AppView = Backbone.View.extend({
        el: '#main',
        show: function (view) {
            this.$el.html(view.el);
        }
    });

    // Collections

    PlantManager.PowerPlantList = Backbone.Collection.extend({
        url: '/api/powerplants'
    });

    // Models

    PlantManager.PowerPlant = Backbone.Model.extend({
        urlRoot: '/api/powerplants'
    });

    // Views

    PlantManager.PowerPlantListView = Backbone.View.extend({
        tagName: 'ul',
        initialize: function () {
            this.listenTo(this.collection, 'sync', this.render);
        },
        render: function () {
            this.$el.empty();
            this.collection.each(this.renderOne, this);
            return this;
        },
        renderOne: function (powerPlant) {
            var view = new PlantManager.PowerPlantListItemView({ model: powerPlant });
            this.$el.append(view.render().el);
        }
    });

    PlantManager.PowerPlantListItemView = Backbone.View.extend({
        tagName: 'li',
        template: _.template($('#tmpl-powerPlantListItem').html()),
        render: function () {
            this.$el.html(this.template(this.model.toJSON()));
            return this;
        }
    });

    PlantManager.PowerPlantView = Backbone.View.extend({
        events: {
            'change #location': 'updateLocation',
            'change #type': 'updateType',
            'change #powerGenerated': 'updatePower',
            'change #maintenanceCost': 'updateCost',
            'click #save': 'save'
        },
        template: _.template($('#tmpl-powerPlantDetails').html()),
        initialize: function () {
            this.listenTo(this.model, 'sync', this.render);
            this.listenTo(this.model, 'create', this.returnToList);
        },
        render: function () {
            this.$el.html(this.template(this.model.toJSON()));
            return this;
        },
        updateLocation: function (e) { this.model.set({ location: $(e.target).val() }); },
        updateType: function (e) { this.model.set({ type: $(e.target).val() }); },
        updatePower: function (e) { this.model.set({ powerGenerated: $(e.target).val() }); },
        updateCost: function (e) { this.model.set({ maintenanceCost: $(e.target).val() }); },
        save: function () {
            this.model.save();
        },
        returnToList: function () {
            PlantManager.router.navigate('');
        }
    });

    // Router

    PlantManager.Router = Backbone.Router.extend({
        routes: {
            '': 'list',
            'powerplants/:id': 'details'
        },
        list: function () {
            var list = new PlantManager.PowerPlantList();
            var view = new PlantManager.PowerPlantListView({ collection: list });
            PlantManager.appView.show(view);
            list.fetch();
        },
        details: function (id) {
            var item = new PlantManager.PowerPlant({ id: id });
            var view = new PlantManager.PowerPlantView({ model: item });
            PlantManager.appView.show(view);
            item.fetch();
        },
    });

    PlantManager.start();

</script>

JavaScriptIntro/Views/Shared/_Layout.cshtml
<!doctype html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Exercises</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900">
    <link rel="stylesheet" href="~/Content/css/style.css" />
    @RenderSection("head", false)
</head>

<body>
    <div class="wrapper">
        <nav>
            <span class="title">Exercises</span>
            <ul>
                <li><a href="@Url.Action("Exercises_1_2", "Exercises")">1.2</a> &middot; </li>
                <li><a href="@Url.Action("Exercises_1_4", "Exercises")">1.4</a> &middot; </li>
                <li><a href="@Url.Action("Exercises_2_1", "Exercises")">2.1</a> &middot; </li>
                <li><a href="@Url.Action("Exercises_2_2", "Exercises")">2.2</a> &middot; </li>
                <li><a href="@Url.Action("Exercises_2_3", "Exercises")">2.3</a> &middot; </li>
                <li><a href="@Url.Action("Exercises_2_4", "Exercises")">2.4</a> &middot; </li>
                <li><a href="@Url.Action("Exercises_3_1", "Exercises")">3.1</a></li>
            </ul>
        </nav>
        @RenderBody()
    </div>
    @RenderSection("script", false)
</body>

</html>